version: "3.9"

services:
  api:
    container_name: rest_api_server
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - sqlite_data:/app/students.db
    environment:
      FLASK_ENV: development
    command: python app.py

volumes:
  sqlite_data:
